server:
  port: 9527
spring:
  application:
    name: microservice-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway-9527.com


info:
  app.name: atguigu-microsevicecloud
  comany.name: www.it.hgits.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservice-provider-dept
    mydept.path: /mydept/**
  ignored-services: microservice-provider-dept
  prefix: /atguigu

