server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entity
  mapper-locations: classpath:mybatis/mappers/**/*.xml

spring:
  application:
    name: microservice-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDb
    username: root
    password: yy123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: microservice-provider-dept

info:
  app.name: atguigu-microservicecloud
  company.name: www.it.hgits.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
